baseURL = "https://AiInfiniteOdyssey.com"
languageCode = "en-us"
title = "AI Infinite Odyssey"
theme = "future-imperfect"  # This MUST match the folder name in /themes/

[params]
  description = "Exploring AI's infinite possibilities."
  dateFormat = "January 2, 2006"
  background = "images/ai-futuristic-bg.jpg"
  landingTitle = "🚀 AI Infinite Odyssey"
  landingSubtitle = "A Podcast About AI & The Future"

  # Fix for deprecated .Site.Social
  [[params.social]]
    name = "GitHub"
    url = "https://github.com/BenjaminWLarson"
  [[params.social]]
    name = "Twitter"
    url = "https://twitter.com/"
  [[params.social]]
    name = "Email"
    url = "mailto:your@email.com"  # This fixes the 404.html error

# Ensure Hugo writes the site output to public/
publishDir = "public"

# Disable RSS feeds and taxonomy pages to prevent unnecessary index.xml files
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]