baseURL = "https://AiInfiniteOdyssey.com"
languageCode = "en-us"
title = "AI Infinite Odyssey"
theme = "future-imperfect"  # This MUST match the folder name in /themes/

[params]
  description = "Exploring AI's infinite possibilities."
  dateFormat = "January 2, 2006"
  background = "images/ai-futuristic-bg.jpg"
  landingTitle = "🚀 AI Infinite Odyssey"
  landingSubtitle = "A Podcast About AI & The Future"

  # Fix for deprecated .Site.Social
  [params.social]
    email = "your@email.com"
    github = "https://github.com/BenjaminWLarson"
    twitter = "https://twitter.com/"

# Disable RSS feeds and taxonomy pages to prevent unnecessary index.xml files
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]