name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main  # Runs on commits to main branch
  workflow_dispatch: # Allows manual deployment trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build Site
        run: |
          hugo --minify --cleanDestinationDir  # This ensures a clean build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}  # Using Personal Access Token
          publish_dir: public  # Only deploy contents of public/
          publish_branch: gh-pages
          force_orphan: true
          cname: AiInfiniteOdyssey.com