name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensures all submodules are cloned

      - name: Update Submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true  # Required for some themes

      - name: Build Site
        run: |
          hugo --minify --cleanDestinationDir
          ls -la themes/  # Debugging: Ensure theme exists

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          cname: AiInfiniteOdyssey.com
