name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: BenjaminWLarson/AiInfiniteOdyssey@main
      env:
        HUGO_VERSION: 0.68.3
        TARGET_REPO: BenjaminWLarson/AiInfiniteOdyssey.github.io
        TOKEN: ${{ secrets.GH_PAT }}
        CNAME: www.AiInfiniteOdyssey.com
